//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.09 at 12:05:08 PM GMT 
//


package wearables;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {

    private final static QName _MyDatabase_QNAME = new QName("", "myDatabase");

    public ObjectFactory() {
    }

    public Database createDatabase() {
        return new Database();
    }

    public Availability createAvailability() {
        return new Availability();
    }

    public Product createProduct() {
        return new Product();
    }

    public Store createStore() {
        return new Store();
    }

    @XmlElementDecl(namespace = "", name = "myDatabase")
    public JAXBElement<Database> createMyDatabase(Database value) {
        return new JAXBElement<Database>(_MyDatabase_QNAME, Database.class, null, value);
    }

}
