//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 12:10:59 PM GMT 
//


package wearables;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Product">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="category">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="SmartJackets"/>
 *               &lt;enumeration value="SmartHeadphones"/>
 *               &lt;enumeration value="SmartGlasses"/>
 *               &lt;enumeration value="SmartWatch"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="colour" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product", propOrder = {
    "id",
    "category",
    "name",
    "brand",
    "colour",
    "description"
})

public class Product {

    @XmlElement(required = true)
    protected BigInteger id;
    @XmlElement(required = true)
    protected String category;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String brand;
    @XmlElement(required = true)
    protected String colour;
    @XmlElement(required = true)
    protected String description;


    public BigInteger getId() {
        return id;
    }

    public void setId(BigInteger value) {
        this.id = value;
    }

    public String getCategory() {
        return category;
    }


    public void setCategory(String value) {
        this.category = value;
    }


    public String getName() {
        return name;
    }

 
    public void setName(String value) {
        this.name = value;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String value) {
        this.brand = value;
    }

    public String getColour() {
        return colour;
    }

    public void setColour(String value) {
        this.colour = value;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        this.description = value;
    }
    
    public String toString() {
    	return "ID: " + id + 
    			"\tCategory: " + category +
    			"\tName: " + name + 
    			"\tBrand: " + brand + 
    			"\tColour: " + colour + 
    			"\tDescription: " + description ;
    }

}
